export interface IResQuotationDetailData {
    e_paper: string;
    sms_send_status: string;
    e_doc_status?: string;
    quo_id: number;
    idcard_num: string;
    phone_number: string;
    email: string;
    dealer_signature_owner: string;
    title_code: string;
    title_name: string;
    first_name: string;
    last_name: string;
    birth_date?: any;
    birth_date_text_th: string;
    birth_date_text_en: string;
    ciz_issued_date: Date;
    ciz_issued_place: string;
    ciz_expired_date: Date;
    ciz_address?: string;
    ciz_sub_district?: string;
    ciz_district?: string;
    ciz_province_name?: string;
    ciz_province_code?: string;
    ciz_postal_code?: string;
    sl_code: string;
    checker_code: string;
    quo_status: number;
    quo_living_place_id: string;
    quo_contract_place_id: string;
    quo_working_place_id: string;
    quo_career_id: string;
    quo_credit_id: string;
    quo_image_id: string;
    user_id: number;
    created_time: Date;
    last_updated_time: Date;
    approved_time?: any;
    face_recog_api_id?: string;
    quo_key_app_id: string;
    quo_purpose_id: string;
    quo_consent_id: string;
    ctp_app_key_id: string;
    ctp_address?: string;
    ctp_sub_district?: string;
    ctp_district?: string;
    ctp_province_name?: string;
    ctp_province_code?: string;
    ctp_postal_code?: string;
    lvp_app_key_id: string;
    lvp_address?: string;
    lvp_sub_district?: string;
    lvp_district?: string;
    lvp_province_name?: string;
    lvp_province_code?: string;
    lvp_postal_code?: string;
    lvp_latitude: string;
    lvp_londtiude: string;
    lvp_lalon: string;
    wp_app_key_id: string;
    wp_address?: string;
    wp_sub_district?: string;
    wp_district?: string;
    wp_province_name?: string;
    wp_province_code?: string;
    wp_postal_code?: string;
    cd_app_key_id: string;
    cd_brand_code?: string;
    cd_brand_code_1?: string;
    cd_status?: number;
    cd_model_code?: string;
    cd_model_name?: string;
    cd_color_code?: string;
    cd_color_name?: string;
    cd_loan_amount?: number;
    cd_productvalue?: number;
    cd_interest_rate?: number;
    cd_payment_value?: number;
    cd_payment_round_count?: number;
    cd_down_payment?: number;
    cd_insurer_code?: string;
    cd_insurer_name?: string;
    cd_insurance_code?: string;
    cd_insurance_name?: string;
    cd_insurance_year?: number;
    cd_insurance_plan_price?: number;
    cd_is_include_loanamount?: number;
    cd_factory_price?: number;
    cd_size_model?: string;
    cd_brand_name?: string;
    cd_net_finance: number;
    // new max ltv field of credit (24/08/2022)
    cd_max_ltv: number;
    // new field form total loss (29/08/2022)
    cd_coverage_total_loss: number,
    cd_price_include_vat: number,
    cd_engine_number: string,
    cd_chassis_number: string,
    cd_engine_no_running: string,
    cd_chassis_no_running: string,
    cr_app_key_id: string;
    cr_main_career_name?: string;
    cr_main_career_code?: string;
    cr_main_workplace_name?: string;
    cr_main_position?: string;
    cr_main_department?: string;
    cr_main_experience_year?: number;
    cr_main_experience_month?: number;
    cr_main_salary_per_month?: number;
    cr_main_salary_per_day?: number;
    cr_main_leader_name?: string;
    cr_main_work_per_week?: number;
    cr_is_sub_career: number;
    cr_sub_career_name?: string;
    cr_sub_career_code?: string;
    cr_sub_workplace_name?: string;
    cr_sub_position?: string;
    cr_sub_department?: string;
    cr_sub_experience_year?: number;
    cr_sub_experience_month?: number;
    cr_sub_salary_per_month?: number;
    cr_sub_salary_per_day?: number;
    cr_sub_leader_name?: string;
    cr_sub_work_per_week?: number;
    cs_app_key_id: string;
    cs_customer_name: string;
    cs_first_name: string;
    cs_last_name?: string;
    cs_is_credit_consent: number;
    cs_is_final_consent?: number;
    cs_is_disclosure_consent: number;
    cs_is_personal_disclosure: number;
    cs_signature_image?: any;
    cs_witness_image?: any;
    is_check_sale_sheet_explain: number,
    is_check_product_detail: number,
    is_check_payment_rule: number,
    is_check_contract_explain: number,
    is_check_total_loss_explain: number,
    is_check_total_loss_company: number,
    is_check_life_insurance: number,
    is_check_l_insur_detail: number,
    is_check_l_insur_plan: number,
    is_check_l_insur_company: number,
    is_check_l_insur_refund: number,
    is_check_l_insur_cancle_d: number,
    pp_app_key_id: string;
    pp_purpose_of_buy?: string;
    pp_purpose_of_buy_name?: string;
    pp_reason_of_buy?: string;
    pp_reason_of_buy_name?: string;
    pp_car_user?: string;
    pp_car_user_name?: string;
    pp_car_user_relation?: string;
    pp_car_user_fullname?: string;
    pp_car_user_citizencard_id?: string;
    pp_car_user_home_no?: string;
    pp_car_user_home_name?: string;
    pp_car_user_soi?: string;
    pp_car_user_trok?: string;
    pp_car_user_moo?: string;
    pp_car_user_road?: string;
    pp_car_user_sub_district?: string;
    pp_car_user_district?: string;
    pp_car_user_province_code?: string;
    pp_car_user_province_name?: string;
    pp_car_user_postal_code?: string;
    pp_car_user_room_no?: string;
    pp_car_user_floor?: string;
    pp_car_user_phoneno?: string;
    pp_first_referral_fullname?: string;
    pp_first_referral_houseno?: string;
    pp_first_referral_moo?: string;
    pp_first_referral_house_name?: string;
    pp_first_referral_room_no?: string;
    pp_first_referral_floor?: string;
    pp_first_referral_soi?: string;
    pp_first_referral_road?: string;
    pp_first_referral_sub_district?: string;
    pp_first_referral_district?: string;
    pp_first_referral_province_n?: string;
    pp_first_referral_province_c?: string;
    pp_first_referral_postal_code?: string;
    pp_first_referral_phoneno?: string;
    pp_first_referral_relation: string;
    pp_second_referral_fullname?: string;
    pp_second_referral_houseno?: string;
    pp_second_referral_moo?: string;
    pp_second_referral_house_name?: string;
    pp_second_referral_room_no?: string;
    pp_second_referral_floor?: string;
    pp_second_referral_soi?: string;
    pp_second_referral_road?: string;
    pp_second_referral_sub_d?: string;
    pp_second_referral_district?: string;
    pp_second_referral_province_n?: string;
    pp_second_referral_province_c?: string;
    pp_second_referral_postal_code?: string;
    pp_second_referral_phoneno?: string;
    pp_second_referral_relation: string;
    atf_app_key_id?: string;
    atf_house_registration_image?: any;
    atf_face_image?: any;
    atf_house_image?: any;
    atf_store_image?: any;
    atf_salary_certificate_image?: any;
    atf_work_certificate_image?: any;
    atf_salary_payment_image?: any;
    atf_bookbank_image?: any;
    atf_motocycle_license_image?: any;
    atf_signature_image?: any;
    atf_citizenid_image?: any;
    atf_citizenid_image_test?: any;
    application_num: string;
    contract_no: string;
    loan_result: string;
    // new value of new PDPA (21/07/2022)
    identity_approve_consent_value?: number;
    motor_insurance_consent_value?: number;
    nmotor_insurance_consent_value?: number;
    analyze_consent_value?: number;
    info_consent_value?: number;
    info_party_consent_value?: number;
    analyze_party_consent_value?: number;
    prdt_info_party_consent_value?: number;
    followup_consent_value?: number;
    info_develop_consent_value?: number;
    // new value of new e-paper (01/08/2022)
    e_paper_consent_value?: number;
    // new house regis place (25/08/2022)
    hrp_app_key_id: string;
    hrp_address: string;
    hrp_sub_district: string;
    hrp_district: string;
    hrp_province_name: string;
    hrp_province_code: string;
    hrp_postal_code: string;
    ciz_gender: number;
    dipchip_uuid: string;
    cizcard_image: any[];
    // === add new 6 fild (maire status, nick name, stay month, stay year , house type , house owner type ) (15/11/2022) ===
    ciz_nickname: string;
    ciz_house_type: number;
    ciz_house_owner_type: number;
    ciz_stayed_year: number;
    ciz_stayed_month: number;
    ciz_maried_status: number;
    ciz_quo_stage: number;


}

export interface IResQuotationDetail {
    data: IResQuotationDetailData[];
    status: number;
    message: string;
}  
